site_name: Wasm4Learn platform documentation
repo_url: https://github.com/IFB-ElixirFr/Wasm4Learn-doc
repo_name: IFB-ElixirFr/Wasm4Learn-doc
copyright: IFB 2023-Present | Licenced under Creative Commons by Share Alike 4.0 International

theme:
  name: material
  features:
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# page tree
nav:
    - Home: index.md
    - Deployment:
      - Tool: Deployment/deployment_01_tool.md
      - Content: Deployment/deployment_02_content.md
      - Doc: Deployment/deployment_03_doc.md
    - Components:
      - Introduction: Components/components_01_intro.md
      - Quizz: Components/components_02_quizz.md
      - Order propositions: Components/components_03_orderProps.md
      - Exercice: Components/components_04_exo.md
      - Admonition: Components/components_05_admonition.md
      - Code: Components/components_06_code.md